# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://chauby.github.io
date_format: "ordinal"
title: Chaobin
subtitle: "The sandglass remembers the time we mislay"
description: "The sandglass remembers the time we mislay"
keywords: 沙漏, 博士的沙漏, Chauby Zou, Chauby, Chaobin Zou 
# timezone: Asia/Chengdu
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Chauby
organization: UESTC
organization_url: http://www.uestc.edu.cn
github_username: Chauby
location: Chengdu, China
email: chaubyZou@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Homepage

  -
    href: /cv/
    label: CV

  -
    href: /publications/
    label: Publications

  -
    href: /categories/
    label: Blog

  -
    href: /wiki/
    label: Wiki

  # -
  #   href: /links/
  #   label: Links

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chauby/chauby.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#     username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: chauby
#     repo: blog-comments
#     oauth:
#         client_id: d2e1cbbd298958076462
#         client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: chauby
#     repo: blog-comments
#     clientID: d2e1cbbd298958076462
#     clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
github: [metadata]
